config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#home'
  get  'posts/search'
  get 'search2' => 'posts#search2'
  get  'posts/part0'
  get  'posts/part1'
  get  'posts/part2'
  get  'posts/part3'
  get  'posts/part4'
  get  'posts/part5'
  get  'posts/part6'
  get  'posts/part7'
  get  'posts/part8'
  get  'posts/strong0'
  get  'posts/strong1'
  get  'posts/strong2'
  get 'users/:id/bookmark' => 'users#bookmark', as: 'users_bookmark'
  resources :users do
    member do
          get :following, :followers
      end
  end
  resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :books, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length: {maximum: 100}
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    #投稿に紐づいたコメントを作成
    @post_comment = @post.post_comments.build(post_comment_params)
    @post_comment.user_id = current_user.id
    @post_comment.save
    render :index
  end

  def destroy
    @post_comment = PostComment.find(params[:id])
    @post_comment.destroy
    render :index
  end

    private
    def post_comment_params
      params.require(:post_comment).permit(:comment, :post_id, :user_id)
    end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_form.html.erb
<%= form_with(model: [post, post_comment]) do |f| %>
    <%= f.text_area :comment, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/post_comments/_index.html.erb
<!-- コメント内容(２件) ------------------------------------------------------------------>
<strong><%= post_comments.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% post_comments.first(2).each do |post_comment| %>
  <% unless post_comment.id.nil? %>
    <div class="comment-container">
        <div>
            <div class="row" style="background: rgba(255,255,255,0.4);margin:5px; padding-top: 5px">
                <div class="col-xs-2">
                    <div>
                        <%= attachment_image_tag post_comment.user, :profile_image, fallback: "no-image.png", class:"comment-image", size: "40x40" %>
                    </div>
                    <div class="comment-text">
                        <p><%= link_to "@#{post_comment.user.name}", users_path(post_comment.user.id) %></p>
                    </div>
                </div>
                <div class="col-xs-9">
                    <div class="comment-entry">
                        <%= post_comment.comment %>
                    </div>
                    <div style="text-align: right">
                        <% if post_comment.user == current_user %>
                            <%= link_to post_post_comment_path(post_comment.post_id, post_comment.id), method: :delete, remote: true, class: "comment_destroy bottom", :style=>"text-decoration:none" do %>
                                削除する
                            <% end %>
                        <% end %>
                    </div>
                    <span class="comment-date pull-right">
                          <%= post_comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                    </span>
                </div>
            </div>
        </div>
    </div>
  <% end %>
<% end %>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
    <div class="collapse" id="collapseExample">
            <% post_comments.offset(2).each do |post_comment| %>
              <% unless post_comment.id.nil? %>
                <div class="comment-container">
                    <div class="row" style="background: rgba(255,255,255,0.4);margin:5px; padding-top: 5px">
                        <div class="col-xs-2">
                            <%= attachment_image_tag post_comment.user, :profile_image, fallback: "no-image.png", class:"comment-image", size: "40x40" %>
                            <p><%= link_to "@#{post_comment.user.name}", users_path(post_comment.user.id) %></p>
                        </div>
                        <div class="col-xs-9">
                            <div>
                                <%= post_comment.comment %>
                            </div>
                            <div style="text-align: right">
                                <% if post_comment.user == current_user %>
                                    <%= link_to post_post_comment_path(post_comment.post_id, post_comment.id), method: :delete, remote: true, class: "comment_destroy bottom", :style=>"text-decoration:none" do %>
                                        削除する
                                    <% end %>
                                <% end %>
                            </div>
                            <span class="comment-date pull-right">
                                  <%= post_comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                            </span>
                        </div>
                    </div>
                </div>
              <% end %>
            <% end %>
    </div>
</strong>

app/views/post_comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { post_comments: @post_comment.post.post_comments }) %>")
$("textarea").val('')