config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#home'
  get  'posts/search'
  get 'search2' => 'posts#search2'
  get  'posts/part0'
  get  'posts/part1'
  get  'posts/part2'
  get  'posts/part3'
  get  'posts/part4'
  get  'posts/part5'
  get  'posts/part6'
  get  'posts/part7'
  get  'posts/part8'
  get  'posts/strong0'
  get  'posts/strong1'
  get  'posts/strong2'
  get 'users/:id/bookmark' => 'users#bookmark', as: 'users_bookmark'
  resources :users do
    member do
          get :following, :followers
      end
  end
  resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :books, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorite, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :booked_posts, through: :books, source: :post

  validates :name, presence: true
  validates :email, presence: true
  validates :introduction, length: {maximum: 100}

  # follow機能
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  #フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  attachment :profile_image

  def already_booked?(post)
    self.books.exists?(post_id: post.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update]

  def index
    

  end

  def show
  	@user = User.find(params[:id])
    @posts = @user.posts.reverse_order.page(params[:page]).per(10)
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def following
    #@userがフォローしているユーザー
    @post = Post.new
    @user  = User.find(params[:id])
    @users = @user.following.reverse_order.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    #@userをフォローしているユーザー
    @post = Post.new
    @user  = User.find(params[:id])
    @users = @user.followers.reverse_order.page(params[:page]).per(10)
    render 'show_follower'
  end

  def bookmark
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
    @post = Post.new
  end

  private
	def user_params
	  params.require(:user).permit(:name, :introduction, :profile_image)
	end

  def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- フォローボタン -->
	<div class="follower">
        <%= link_to followers_user_path(user.id) do %>
          <h4 style="color: black;">フォロワー<%= user.followers.count %>人</h5>
        <% end %>
      </div>
      <div class="follow">
        <%= link_to following_user_path(user.id) do %>
          <h4 style="color: black;">フォロー<%= user.following.count %>人</h5>
        <% end %>
      </div>
<% if user != current_user%>

    <% if current_user.following?(user) %>
      <%= form_for(current_user, url: relationship_path(user), method: :delete, remote: true) do |f| %>
        <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
      <% end %>
    <% else %>
	  <%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
        <%= hidden_field_tag :following_id, user.id %>
        <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
      <% end %>
    <% end %>

<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/bookmark.html.erb
<div class="row">
  <div class="col-lg-6"id="post_index">

    <div class="main-profile">
      <div class="row">
        <div class="col-xs-6">
          <div style="margin-left: 45px;">
            <%= attachment_image_tag(@user, :profile_image, :fill, 200, 200, fallback: "no-image.png",size: "200x200", class: "img3") %>
          </div>
        </div>
        <div class="col-xs-6">
          <h3>
            <strong><%= @user.name %></strong>
          </h3>
          <!-- フォロー機能 -->
          <div id="follow_form_<%= @user.id%>" style="margin: 40px 0;">
              <%= render "follow_form",user: @user %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <h4 style="text-align: center; margin-top: 30px;">
                <strong style="border-bottom: solid 2px;">プロフィール</strong>
            </h4>
            <h5 style="padding: 8px;">
              <strong>
              <%= @user.introduction %>
            </strong>
            </h5>

            <% if @user.id == current_user.id %>
              <h4 style="text-align: center;margin-top: 30px;">
                <%= link_to 'プロフィール編集',edit_user_path(@user), :style=>"text-decoration: none;", class: "bottom edit_user_#{@user.id} " %>
              </h4>
              <h4 style="text-align: center">
                <%= link_to '投稿一覧', user_path(@user), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
              <h4 style="text-align: center;">
                <%= link_to 'トレーニングを投稿する', new_post_path(@post), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-6">
    <div style="width: 100%;margin-top: 40px;">
      <div>
        <h2>ブックマーク一覧</h2>
      </div>

      <% @user.booked_posts.each do |post| %>
      <strong>
        <div class="post_index">
          <div class="row">
            <div class="col-xs-4">
              <div style="margin: 30px 0 0 20px;"><%= attachment_image_tag(post.user, :profile_image, :fill, 100, 100, fallback: "no-image.png",size: "130x130", class: "img") %></div>
              <h4>投稿者：<%= link_to(post.user.name,"/users/#{post.user.id}") %></h4>
            </div>
            <div class="col-xs-7">
              <h4>
                <strong style="border-left: 11px solid #9caeb7;padding: 5px 10px 5px 8px;background: #d0dee5;margin: 15px;"><%= link_to post.title,post, class: "post_#{post.id}", :style=>"text-decoration:none;" %>
                </strong>
              </h4>
              <p>効果部位：<%= post.part_i18n %></p>
              <p>強度：<%= post.strong_i18n %></p>
              <%= render 'posts/tag_list', tag_list: post.tag_list %>
              <div style="margin-top: 8px;">
                コメント数　<%= post.post_comments.count %> &emsp;&emsp;
                いいね数　<%= post.favorites.count%>
              </div>
              <div style="margin-top: 8px;">
                投稿日：<%= post.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            </div>
          </div>
        </div>
        </div>
      </strong>
      <% end %>
      <div style="margin-bottom: 100px;">
        <%= paginate @posts %>
      </div>

    </div>
  </div>

</div>

app/views/users/edit.html.erb
<div class="row"id="post_index">
  <div style="width: 95%; margin-left: 10px">
  <div>
    <h2 class="text-center">
      <strong>プロフィール編集</strong>
    </h2>

    <%= form_for(@user) do |f| %>
      <div class="form_group">
        <br>
        <h4>
            <strong>ユーザー名</strong>
        </h4>
        <%= f.text_field :name, placeholder: "ユーザー名を入力してください", class: "form-control" %>
      </div><br>

      <div class="form-group" >
        <br>
        <h4>
            <strong>プロフィール</strong>
        </h4>
        <%= f.text_area :introduction, placeholder: "プロフィールを入力してください", rows: 7, class: "form-control" %>
      </div>

      <div style="text-align: center;">
        <div class="wrapper image_box">
          <div style="width: 300px; margin-right: 10px">
            <div style="margin: 40px; text-align: center">
              <%= attachment_image_tag @user, :profile_image, :limit, 300, 300, fallback: "no-image.png",id:"prev_img", :style=>"width:300px;" %>
            </div>
            <label for="post_img" class= "bottom" style="width: auto; margin: 20px 0;font-size: 20px; padding: 5px;">
              <%= f.attachment_field :profile_image,id: :post_img, class: "hidden" %>
              プロフィール画像の選択
            </label>
          </div>
        </div>

        <h2 class="text-center" style="margin-top: 80px;">
          <strong>アカウント情報</strong>
        </h2>

        <h3 class="wrapper2">
          <strong>メールアドレス</strong>
        </h3>

        <div class="wrapper">
          <%= f.text_field :email, placeholder: "ユーザー名を入力してください", class: "form-control" %>
        </div>

        <div style="margin: 100px 0;">
          <%= f.submit "更新する" %>
        </div>

    <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row"id="post_index">
  <div class="col-lg-6">

    <div class="main-profile">
      <div class="row">
        <div class="col-xs-6">
          <div style="margin-left: 45px;">
            <%= attachment_image_tag(@user, :profile_image, :fill, 200, 200, fallback: "no-image.png",size: "200x200", class: "img3") %>
          </div>
        </div>
        <div class="col-xs-6">
          <h3>
            <strong><%= @user.name %></strong>
          </h3>
          <!-- フォロー機能 -->
          <div id="follow_form_<%= @user.id%>" style="margin: 40px 0;">
              <%= render "follow_form",user: @user %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <h4 style="text-align: center; margin-top: 30px;">
                <strong style="border-bottom: solid 2px;">プロフィール</strong>
            </h4>
            <h5 style="padding: 8px;">
              <strong>
              <%= @user.introduction %>
            </strong>
            </h5>

            <% if @user.id == current_user.id %>
              <h4 style="text-align: center;margin-top: 30px;">
                <%= link_to 'プロフィール編集',edit_user_path(@user), :style=>"text-decoration: none;", class: "bottom edit_user_#{@user.id} " %>
              </h4>
              <h4 style="text-align: center">
                <%= link_to 'ブックマーク一覧', users_bookmark_path(@user), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
              <h4 style="text-align: center;">
                <%= link_to 'トレーニングを投稿する', new_post_path(@post), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-6">
    <div style="width: 100%;margin-top: 40px;">
      <div>
        <h2>投稿一覧</h2>
      </div>

      <% @posts.each do |post| %>
      <strong>
        <div class="post_index">
          <div class="row">
            <div class="col-xs-4">
              <div style="margin: 30px 0 0 20px;"><%= attachment_image_tag(post.user, :profile_image, :fill, 100, 100, fallback: "no-image.png",size: "130x130", class: "img") %></div>
              <h4>投稿者：<%= link_to(post.user.name,"/users/#{post.user.id}") %></h4>
            </div>
            <div class="col-xs-7">
              <h4>
                <strong style="border-left: 11px solid #9caeb7;padding: 5px 10px 5px 8px;background: #d0dee5;margin: 15px;"><%= link_to post.title,post, class: "post_#{post.id}", :style=>"text-decoration:none;" %>
                </strong>
              </h4>
              <p>効果部位：<%= post.part_i18n %></p>
              <p>強度：<%= post.strong_i18n %></p>
              <%= render 'posts/tag_list', tag_list: post.tag_list %>
              <div style="margin-top: 8px;">
                コメント数　<%= post.post_comments.count %> &emsp;&emsp;
                いいね数　<%= post.favorites.count%>
              </div>
              <div style="margin-top: 8px;">
                投稿日：<%= post.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            </div>
          </div>
        </div>
        </div>
      </strong>
      <% end %>
      <div style="margin-bottom: 100px;">
        <%= paginate @posts %>
      </div>

    </div>
  </div>

</div>

app/views/users/show_follow.html.erb
<div class="row"id="post_index">
  <div class="col-lg-6">

    <div class="main-profile">
      <div class="row">
        <div class="col-xs-6">
          <div style="margin-left: 45px;">
            <%= attachment_image_tag(@user, :profile_image, :fill, 200, 200, fallback: "no-image.png",size: "200x200", class: "img3") %>
          </div>
        </div>
        <div class="col-xs-6">
          <h3>
            <strong><%= @user.name %></strong>
          </h3>
          <!-- フォロー機能 -->
          <div id="follow_form_<%= @user.id%>" style="margin: 40px 0;">
              <%= render "follow_form", user: @user %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <h4 style="text-align: center; margin-top: 30px;">
                <strong style="border-bottom: solid 2px;">プロフィール</strong>
            </h4>
            <h5 style="padding: 8px;">
              <strong>
              <%= @user.introduction %>
            </strong>
            </h5>

            <% if @user.id == current_user.id %>
              <h4 style="text-align: center;margin-top: 30px;">
                <%= link_to 'プロフィール編集',edit_user_path(@user), :style=>"text-decoration: none;", class: "bottom edit_user_#{@user.id} " %>
              </h4>
              <h4 style="text-align: center">
                <%= link_to 'ブックマーク一覧', users_bookmark_path(@user), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
              <h4 style="text-align: center;">
                <%= link_to 'トレーニングを投稿する', new_post_path(@post), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-6">
  	<h2 style="margin-top: 40px;">フォロー中</h2>
		<% @user.following.each do |user| %>
    <div class="row" style="background: rgba(255,255,255,0.6);padding:5px;margin:5px;">
      <div class="col-xs-5">
        <%= attachment_image_tag(user, :profile_image, :fill, 200, 200, fallback: "no-image.png",size: "200x200", class: "img") %>
        <%= link_to(user.name,"/users/#{user.id}") %>
      </div>
      <div class="col-xs-7">
        <div id="follow_form_<%= user.id%>"><%= render "follow_form", user: user %></div>
      </div>
    </div>
		<% end %>
	</div>

</div>

app/views/users/show_follower.html.erb
<div class="row"id="post_index">
  <div class="col-lg-6">

    <div class="main-profile">
      <div class="row">
        <div class="col-xs-6">
          <div style="margin-left: 45px;">
            <%= attachment_image_tag(@user, :profile_image, :fill, 200, 200, fallback: "no-image.png",size: "200x200", class: "img3") %>
          </div>
        </div>
        <div class="col-xs-6">
          <h3>
            <strong><%= @user.name %></strong>
          </h3>
          <!-- フォロー機能 -->
          <div id="follow_form_<%= @user.id%>" style="margin: 40px 0;">
              <%= render "follow_form", user: @user %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <h4 style="text-align: center; margin-top: 30px;">
                <strong style="border-bottom: solid 2px;">プロフィール</strong>
            </h4>
            <h5 style="padding: 8px;">
              <strong>
              <%= @user.introduction %>
            </strong>
            </h5>

            <% if @user.id == current_user.id %>
              <h4 style="text-align: center;margin-top: 30px;">
                <%= link_to 'プロフィール編集',edit_user_path(@user), :style=>"text-decoration: none;", class: "bottom edit_user_#{@user.id} " %>
              </h4>
              <h4 style="text-align: center">
                <%= link_to 'ブックマーク一覧', users_bookmark_path(@user), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
              <h4 style="text-align: center;">
                <%= link_to 'トレーニングを投稿する', new_post_path(@post), :style=>"text-decoration: none;", class: "bottom" %>
              </h4>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-6">
  	<h2 style="margin-top: 40px;">フォロワー</h2>
	  <% @user.followers.each do |user| %>
    <div class="row" style="background: rgba(255,255,255,0.6);padding:5px;margin:5px;">
      <div class="col-xs-5">
        <%= attachment_image_tag(user, :profile_image, :fill, 200, 200, fallback: "no-image.png",size: "200x200", class: "img") %>
        <%= link_to(user.name,"/users/#{user.id}") %>
      </div>
      <div class="col-xs-7">
        <div id="follow_form_<%= user.id%>"><%= render "follow_form", user: user %></div>
      </div>
    </div>
	<% end %>
	</div>

</div>