config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#home'
  get  'posts/search'
  get 'search2' => 'posts#search2'
  get  'posts/part0'
  get  'posts/part1'
  get  'posts/part2'
  get  'posts/part3'
  get  'posts/part4'
  get  'posts/part5'
  get  'posts/part6'
  get  'posts/part7'
  get  'posts/part8'
  get  'posts/strong0'
  get  'posts/strong1'
  get  'posts/strong2'
  get 'users/:id/bookmark' => 'users#bookmark', as: 'users_bookmark'
  resources :users do
    member do
          get :following, :followers
      end
  end
  resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :books, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :booked_users, through: :books, source: :user

  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 500}
  validates :tag_list, presence: true

  enum part: [:part0, :part1, :part2, :part3, :part4, :part5, :part6, :part7, :part8]
  # 0=胸 1=背中 2=肩 3=腕 4=腹筋 5=太腿 6=上半身全体 7=下半身全体 8=その他

  enum strong: [:strong0, :strong1, :strong2]
  # 0=軽め 1=普通 2=強め

  attachment :start_image
  attachment :finish_image

  # タグ付
  acts_as_taggable

  # 動画投稿機能
  mount_uploader :video, VideoUploader

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
      if search
        Post.where(['title LIKE ?', "%#{search}%"])
      else
        Post.all
      end
  end

  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'likes'
      return Post.find(Favorite.group(:post_id).order('count(post_id) desc').pluck(:post_id))
    when 'dislikes'
      return Post.find(Favorite.group(:post_id).order(Arel.sql('count(post_id) asc')).pluck(:post_id))
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,only: [:new, :show, :create,:edit,:update,:destroy]

  def new
    @post = Post.new
    @post.post_images.build
  end

  def index
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @strongs = Post.select("strong")
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @tags = ActsAsTaggableOn::Tag.all
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def show
    @post = Post.find(params[:id])
    @book = Book.new
    @post_comment = PostComment.new
    #新着順で表示
    @post_comments = @post.post_comments.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
    screen_user(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      @posts = Post.all
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url
  end

  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @posts = Post.search(params[:search]).reverse_order.page(params[:page]).per(10)
    #@posts = @posts.page(params[:page]).per(3)
    @search = params[:search]
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @tags = ActsAsTaggableOn::Tag.all
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def search2
    selection = params[:keyword]
    @posts = Post.sort(selection).reverse_order.page(params[:page]).per(10)
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @tags = ActsAsTaggableOn::Tag.all
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
 end

  def part0
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part1
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @strongs = Post.select("strong")
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @tags = ActsAsTaggableOn::Tag.all
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part2
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part3
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part4
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part5
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part6
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part7
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def part8
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def strong0
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def strong1
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  def strong2
    @post = Post.new
    @posts = Post.all.reverse_order.page(params[:page]).per(10)
    @user = @post.user
    @tags = ActsAsTaggableOn::Tag.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
      # @posts = @posts.page(params[:page]).per(10)
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :strong, :part, :start_image, :finish_image, :video, :tag_list, post_images_images: [])
    end

    def screen_user(post)
      if post.user.id != current_user.id
        redirect_to posts_path
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_search_form.html.erb
<div style="width: 80%;margin: 20px 0 30px 20px;">
  <h3>トレーニングを検索する</h3>
  <%= form_tag(posts_search_path,:method => 'get') do %>
    <%= text_field_tag :search, '',placeholder: "トレーニング名を入力してください" %>
    <%= submit_tag '検索する', :title => nil, class:"button5" %>
  <% end %>
</div>

app/views/posts/_tag_list.html.erb
タグ：
<% count = 0 %>
<% tag_list.each do |tag| %>
	<% if count == 2 %>
		<% count = 0 %>
	<% end %>
	<%= link_to posts_path(tag_name: tag), style:"text-decoration: none;" do %>
   		<%= tag %>
   	<% end %>
   	<% count = count + 1 %>
<% end %>

app/views/posts/index.html.erb
<div id="top"></div>
<div class="row" id="post_index">

  <!-- 検索フォーム -->
  <%= render 'posts/search_form' %>

  <div class="col-lg-6">

    <!-- 投降一覧 -->
    <h2>投稿一覧</h2>
    <strong>
  	  <% @posts.each do |post| %>
  	    <%= render 'posts/post_index', post: post %>
  	  <% end %>
      <div style="margin-bottom: 100px;">
        <%= paginate @posts %>
      </div>
    </strong>
  </div>


  <div class="col-lg-6">

    <!-- 人気投稿 -->
    <h2 style="text-align: center">人気投稿</h2>
    <strong>
      <% @all_ranks.each do |post| %>
        <%= render 'posts/post_index', post: post %>
      <% end %>
    </strong>


    <!-- タグ一覧 -->
    <h2 class="side">タグで検索</h2>
    <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
      <div style="margin: 5px 3px;">
        <% @tags.each do |tag| %>
          <%= link_to posts_path(tag_name: tag.name), style:"text-decoration: none;" do %>
            <%= tag %>
          <% end %>
        <% end %>
      </div>
    </h3>

    <div class="row">

      <!-- 効果部位一覧 -->
      <div class="col-xs-6">
        <h2 class="side">効果部位で検索</h2>
        <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
          <div style="margin: 5px 3px;">
            <%= link_to posts_part0_path, :style=>"text-decoration:none;" do %>
            胸
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part1_path, :style=>"text-decoration:none;" do %>
            背中
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part2_path, :style=>"text-decoration:none;" do %>
            肩
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part3_path, :style=>"text-decoration:none;" do %>
            腕
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part4_path, :style=>"text-decoration:none;" do %>
            腹筋
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part5_path, :style=>"text-decoration:none;" do %>
            太腿
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part6_path, :style=>"text-decoration:none;" do %>
            上半身全体
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part7_path, :style=>"text-decoration:none;" do %>
            下半身全体
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part8_path, :style=>"text-decoration:none;" do %>
            その他
            <% end %>
          </div>
        </h3>
        <h2 style="text-align: center" style="margin-top: 20px;">公式ツイッター</h2>
        <a class="twitter-timeline" href="https://twitter.com/note_muscle?ref_src=twsrc%5Etfw">Tweets by note_muscle</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>

      <!-- 強度一覧 -->
      <div class="col-xs-6">
        <h2 class="side">強度で検索</h2>
        <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
          <div style="margin: 5px 3px;">
            <%= link_to posts_strong0_path, :style=>"text-decoration:none;" do %>
            軽め
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_strong1_path, :style=>"text-decoration:none;" do %>
            普通
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_strong2_path, :style=>"text-decoration:none;" do %>
            強め
            <% end %>
          </div>
      </div>
    </div>
    <div class="org_to_top">
    <a href="#top">
      <div class="m_to_top">
      ↑
      </div>
    </a>
  </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="row"id="post_index">
  <div style="width: 90%; margin-left: 15px">
	  <h2 class="text-center pt-5">
	  	<strong>新規投稿</strong>
	  </h2>
    <div style="color: red">
      <%= render "devise/shared/error_messages", resource: @post %>
    </div>

		<%= form_for(@post) do |f| %>
    <div class="form_group">
  	  <br>
      <h4>
        <strong>トレーニング名</strong>
      </h4>
      <%= f.text_field :title, placeholder: "トレーニング名を入力してください 例：腕立て伏せ", class: "form-control" %>
    </div>
    <br>

	  <div class="form-group" >
	  	<br>
	    <h4>
	      <strong>トレーニング内容</strong>
	    </h4>
	    <%= f.text_area :body, placeholder: "トレーニング内容,セット数などを入力してください
・10~15回　3セット", rows: 7, class: "form-control" %>
	  </div>

    <div class="form-group" >
    	<br>
      <h4>
      	<strong>動画選択</strong>
      </h4>
        <%= f.file_field :video, :accept => 'video/*' %>
    </div>

    <div class="form-group" >
    	<br>
      <h4>
      	<strong>画像選択（複数選択可能）</strong>
      </h4>
        <%= f.attachment_field :post_images_images,id: :post_img, multiple: true %>
    </div>

    <br>
	  <h4>
	  	<strong>
	    効果部位：<%= f.select :part, Post.parts.keys.map {|k| [I18n.t("enums.post.part.#{k}"), k]} %> &emsp; &emsp;
	    強度：<%= f.select :strong, Post.strongs.keys.map {|k| [I18n.t("enums.post.strong.#{k}"), k]} %>
	    </strong>
	  </h4>
	  <br>

	  <div class="form-group" >
	  	<br>
	  	<h4>
	  		<strong>タグ（複数記入可能）</strong>
	  		<strong>複数記入される場合はカンマで区切ってください</strong>
	  	</h4>
	    <%= f.text_field :tag_list, placeholder: "記入例：大胸筋,肩", value: @post.tag_list.join(','), class: "form-control"%>
	  </div>
    <br>

    <div style="margin-bottom: 100px; text-align: center;">
      <%= f.submit "投稿する" %>
    </div>
		<% end %>
	</div>
</div>

app/views/posts/part0.html.erb
<div id="top"></div>
<div class="row" id="post_index">

  <!-- 検索フォーム -->
  <%= render 'posts/search_form' %>

  <div class="col-lg-6">

    <!-- 投稿一覧 -->
    <h2>効果部位で検索：胸</h2>
    <strong>
      <% @posts.each do |post| %>
      <% if post.part == 'part0' %>
        <%= render 'posts/post_index', post: post %>
      <% end %>
      <% end %>
      <div style="margin-bottom: 100px;">
        <%= paginate @posts %>
      </div>
    </strong>
  </div>


  <div class="col-lg-6">

    <!-- 人気投稿 -->
    <h2 style="text-align: center">人気投稿</h2>
    <strong>
      <% @all_ranks.each do |post| %>
        <%= render 'posts/post_index', post: post %>
      <% end %>
    </strong>


    <!-- タグ一覧 -->
    <h2 class="side">タグで検索</h2>
    <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
      <div style="margin: 5px 3px;">
        <% @tags.each do |tag| %>
          <%= link_to posts_path(tag_name: tag.name), style:"text-decoration: none;" do %>
            <%= tag %>
          <% end %>
        <% end %>
      </div>
    </h3>

    <div class="row">

      <!-- 効果部位一覧 -->
      <div class="col-xs-6">
        <h2 class="side">効果部位で検索</h2>
        <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
          <div style="margin: 5px 3px;">
            胸
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part1_path, :style=>"text-decoration:none;" do %>
            背中
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part2_path, :style=>"text-decoration:none;" do %>
            肩
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part3_path, :style=>"text-decoration:none;" do %>
            腕
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part4_path, :style=>"text-decoration:none;" do %>
            腹筋
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part5_path, :style=>"text-decoration:none;" do %>
            太腿
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part6_path, :style=>"text-decoration:none;" do %>
            上半身全体
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part7_path, :style=>"text-decoration:none;" do %>
            下半身全体
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part8_path, :style=>"text-decoration:none;" do %>
            その他
            <% end %>
          </div>
        </h3>
        <h2 style="text-align: center" style="margin-top: 20px;">公式ツイッター</h2>
        <a class="twitter-timeline" href="https://twitter.com/note_muscle?ref_src=twsrc%5Etfw">Tweets by note_muscle</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>

      <!-- 強度一覧 -->
      <div class="col-xs-6">
        <h2 class="side">強度で検索</h2>
        <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
          <div style="margin: 5px 3px;">
            <%= link_to posts_strong0_path, :style=>"text-decoration:none;" do %>
            軽め
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_strong1_path, :style=>"text-decoration:none;" do %>
            普通
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_strong2_path, :style=>"text-decoration:none;" do %>
            強め
            <% end %>
          </div>
      </div>
    </div>
    <div class="org_to_top">
    <a href="#top">
      <div class="m_to_top">
      ↑
      </div>
    </a>
  </div>

  </div>
</div>

app/views/posts/part1.html.erb
<div id="top"></div>
<div class="row" id="post_index">

  <!-- 検索フォーム -->
  <%= render 'posts/search_form' %>

  <div class="col-lg-6">

    <!-- 投降一覧 -->
    <h2>効果部位で検索：背中</h2>
    <strong>
  	  <% @posts.each do |post| %>
      <% if post.part == 'part1' %>
  	    <%= render 'posts/post_index', post: post %>
      <% end %>
  	  <% end %>
      <div style="margin-bottom: 100px;">
        <%= paginate @posts %>
      </div>
    </strong>
  </div>


  <div class="col-lg-6">

    <!-- 人気投稿 -->
    <h2 style="text-align: center">人気投稿</h2>
    <strong>
      <% @all_ranks.each do |post| %>
        <%= render 'posts/post_index', post: post %>
      <% end %>
    </strong>


    <!-- タグ一覧 -->
    <h2 class="side">タグで検索</h2>
    <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
      <div style="margin: 5px 3px;">
        <% @tags.each do |tag| %>
          <%= link_to posts_path(tag_name: tag.name), style:"text-decoration: none;" do %>
            <%= tag %>
          <% end %>
        <% end %>
      </div>
    </h3>

    <div class="row">

      <!-- 効果部位一覧 -->
      <div class="col-xs-6">
        <h2 class="side">効果部位で検索</h2>
        <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
          <div style="margin: 5px 3px;">
            <%= link_to posts_part0_path, :style=>"text-decoration:none;" do %>
            胸
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            背中
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part2_path, :style=>"text-decoration:none;" do %>
            肩
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part3_path, :style=>"text-decoration:none;" do %>
            腕
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part4_path, :style=>"text-decoration:none;" do %>
            腹筋
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part5_path, :style=>"text-decoration:none;" do %>
            太腿
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part6_path, :style=>"text-decoration:none;" do %>
            上半身全体
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part7_path, :style=>"text-decoration:none;" do %>
            下半身全体
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_part8_path, :style=>"text-decoration:none;" do %>
            その他
            <% end %>
          </div>
        </h3>
        <h2 style="text-align: center" style="margin-top: 20px;">公式ツイッター</h2>
        <a class="twitter-timeline" href="https://twitter.com/note_muscle?ref_src=twsrc%5Etfw">Tweets by note_muscle</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>

      <!-- 強度一覧 -->
      <div class="col-xs-6">
        <h2 class="side">強度で検索</h2>
        <h3 style="padding: 15px; background: rgba(200,240,255,0.3);">
          <div style="margin: 5px 3px;">
            <%= link_to posts_strong0_path, :style=>"text-decoration:none;" do %>
            軽め
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_strong1_path, :style=>"text-decoration:none;" do %>
            普通
            <% end %>
          </div>

          <div style="margin: 5px 3px;">
            <%= link_to posts_strong2_path, :style=>"text-decoration:none;" do %>
            強め
            <% end %>
          </div>
      </div>
    </div>
    <div class="org_to_top">
    <a href="#top">
      <div class="m_to_top">
      ↑
      </div>
    </a>
  </div>

  </div>
</div>