config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#home'
  get  'posts/search'
  get 'search2' => 'posts#search2'
  get  'posts/part0'
  get  'posts/part1'
  get  'posts/part2'
  get  'posts/part3'
  get  'posts/part4'
  get  'posts/part5'
  get  'posts/part6'
  get  'posts/part7'
  get  'posts/part8'
  get  'posts/strong0'
  get  'posts/strong1'
  get  'posts/strong2'
  get 'users/:id/bookmark' => 'users#bookmark', as: 'users_bookmark'
  resources :users do
    member do
          get :following, :followers
      end
  end
  resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :books, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <span>© 2020 katayama</span>
</footer>

app/views/layouts/_header.html.erb
<div style="height: 100px; width: auto">
  <div style="text-align: center;background-color: black;height: 140px;">
  <%= link_to(("/"), :style=>"text-decoration: none;", data: {"turbolinks" => false}) do %>
    <%= image_tag asset_path("logo.png") %>
  <% end %>
  </div>
</div>
<div style="text-align: center; font-size: 20px;margin-bottom: 50px;">
  <% if user_signed_in? %>
    <%= link_to ' マイページ',user_path(current_user), :style=>"text-decoration: none;text-shadow: 2px 2px 2px rgba(20, 20, 20, 0.5);", class: "bottom" %>
    <%= link_to ' 投稿する',new_post_path(@post), :style=>"text-decoration: none;text-shadow: 2px 2px 2px rgba(20, 20, 20, 0.5);", class: "bottom" %>
    <%= link_to "投稿一覧", posts_path, :style=>"text-decoration: none;text-shadow: 2px 2px 2px rgba(20, 20, 20, 0.5);", class: "bottom" %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :style=>"text-decoration: none;text-shadow: 2px 2px 2px rgba(20, 20, 20, 0.5);", class: "bottom" %>
  <% else %>
    <%= link_to "投稿一覧", posts_path, :style=>"text-decoration: none;text-shadow: 2px 2px 2px rgba(20, 20, 20, 0.5);", class: "bottom" %>
    <%= link_to "新規登録", new_user_registration_path, data: {"turbolinks" => false}, :style=>"text-decoration: none;text-shadow: 2px 2px 2px rgba(20, 20, 20, 0.5);", class: "bottom" %>
    <%= link_to "ログイン", new_user_session_path, :style=>"text-decoration: none;text-shadow: 2px 2px 2px rgba(20, 20, 20, 0.5);", class: "bottom" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuscleNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="wrapper">
    

    <div class='body'>
      <div class='container'>

    <%= yield %>

      </div>
    </div>

    <%= render 'layouts/footer' %>
    </div>

  </body>
</html>